export const SHOW_ALL_TODOS_ACTION = "SHOW_ALL_TODOS_ACTION"; 
export type SHOW_ALL_TODOS_ACTIONS = typeof SHOW_ALL_TODOS_ACTION;  

export const SHOW_ALL_COMPLETED_TODOS_ACTION = "SHOW_ALL_COMPLETED_TODOS_ACTION"; 
export type SHOW_ALL_COMPLETED_TODOS_ACTIONS = typeof SHOW_ALL_COMPLETED_TODOS_ACTION; 

export const SHOW_ALL_ACTIVE_TODOS_ACTION = "SHOW_ALL_ACTIVE_TODOS_ACTION"; 
export type SHOW_ALL_ACTIVE_TODOS_ACTIONS = typeof SHOW_ALL_ACTIVE_TODOS_ACTION; 