export const ADD_TODO_ACTION = 'ADD_TODO_ACTION';
export type ADD_TODO_ACTION = typeof ADD_TODO_ACTION;


export const TOGGLE_TODO_ACTION = 'TOGGLE_TODO_ACTION';
export type TOGGLE_TODO_ACTION = typeof TOGGLE_TODO_ACTION;

export const DELETE_TODO_ACTION = 'DELETE_TODO_ACTION';
export type DELETE_TODO_ACTION = typeof DELETE_TODO_ACTION;